<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<DisableDiagnosticTracing>true</DisableDiagnosticTracing>
		
		<MinVerTagPrefix>v</MinVerTagPrefix>
		<MinVerDefaultPreReleaseIdentifiers>dev</MinVerDefaultPreReleaseIdentifiers>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="../Unai.ExtendedBinaryWaterfall/Unai.ExtendedBinaryWaterfall.csproj" />
	</ItemGroup>

</Project>
