<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Unai.ExtendedBinaryWaterfall.Gui.EtoForms\Unai.ExtendedBinaryWaterfall.Gui.EtoForms.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Eto.Platform.Wpf" Version="2.11.0" />
	</ItemGroup>

</Project>
