<Project Sdk="Microsoft.NET.Sdk">
	
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Unai.ExtendedBinaryWaterfall.Gui.EtoForms\Unai.ExtendedBinaryWaterfall.Gui.EtoForms.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Eto.Platform.Gtk" Version="2.11.0" />
		<!-- The following package is deprecated, but without it, `libgtk-3.0.dll` doesn't exist. -->
		<PackageReference Include="GtkSharp.Dependencies" Version="1.1.0" />
	</ItemGroup>
	
</Project>
