using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace Unai.ExtendedBinaryWaterfall.Parsers.WindowsImage;

[Parser("wim", "Windows Image (WIM)", [ ".wim" ])]
public class WindowsImageParser : IParser
{
	public Stream InputStream { get; set; }
	public Stream AuxiliaryInputStream { get; set; }

	private StreamReader _auxInputSr = null;

	public IEnumerable<SubFile> GetSubFiles()
	{
		var ret = ParseWimDir();
		ret = [.. ret
			.Where(sf => sf.Length > 0)
			.GroupBy(sf => sf.StartOffset)
			.Select(sfg => sfg.FirstOrDefault())
			.OrderBy(sf => sf.StartOffset)];

		long lastFileEndOfs = 0;

		foreach (var sf in ret)
		{
			yield return sf;
			if (sf.EndOffset > lastFileEndOfs) lastFileEndOfs = sf.EndOffset;
		}

		yield return new("WIM File Table", lastFileEndOfs, InputStream.Length - lastFileEndOfs) { IconString = "🔶" };
	}

	private IEnumerable<SubFile> ParseWimDir()
	{
		if (AuxiliaryInputStream == null) throw new InvalidOperationException("The WIM parser needs a list of the files stored in a separate text file generated by `wimdir`.");
		if (!AuxiliaryInputStream.CanRead) throw new InvalidOperationException("The WIM file listing is not readable.");

		_auxInputSr ??= new StreamReader(AuxiliaryInputStream);

		bool firstLine = true;
		string filePath = null;
		long fileSize = 0;
		long fileOffset = 0;
		int fileAttrFlags = 0;

		string line;
		while ((line = _auxInputSr.ReadLine()) != null)
		{
			if (line.StartsWith("--------"))
			{
				if (!firstLine)
				{
					yield return new(filePath, fileOffset, fileSize) { IsDirectory = (fileAttrFlags & 0x10) == 0x10 };
				}
				firstLine = false;
			}
			string[] kvp = line.Split(" = ", 2);
			if (line.StartsWith("Full Path"))
			{
				filePath = kvp[1][1..^1];
			}
			else if (line.StartsWith("Compressed size"))
			{
				fileSize = long.Parse(kvp[1].Split(' ')[0]);
			}
			else if (line.StartsWith("Offset in WIM") || line.StartsWith("Solid offset"))
			{
				fileOffset = long.Parse(kvp[1].Split(' ')[0]);
			}
			else if (line.StartsWith("Attributes"))
			{
				fileAttrFlags = int.Parse(kvp[1][2..], System.Globalization.NumberStyles.HexNumber);
			}
		}

		_auxInputSr.Close();

		yield return new(filePath, fileOffset, fileSize) { IsDirectory = (fileAttrFlags & 0x10) == 0x10 };
	}
}