name: Main

on:
  push:
    branches:
    - main
    - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      # The following options are required for version calculation.
      with:
        fetch-depth: 100
        fetch-tags: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.x
    - name: Restore dependencies
      run: cd src && dotnet restore
    - name: Build (CLI)
      run: cd src && dotnet build --no-restore Unai.ExtendedBinaryWaterfall.Cli
    - name: Build (EtoForms GTK GUI)
      run: cd src && dotnet build --no-restore Unai.ExtendedBinaryWaterfall.Gui.EtoForms.Gtk

    - name: Upload artifact (CLI)
      uses: actions/upload-artifact@v4
      with:
        name: ebw-cli
        path: ${{ github.workspace }}/artifacts/bin/Unai.ExtendedBinaryWaterfall.Cli/debug
    - name: Upload artifact (EtoForms GTK GUI)
      uses: actions/upload-artifact@v4
      with:
        name: ebw-etoforms-gtk
        path: ${{ github.workspace }}/artifacts/bin/Unai.ExtendedBinaryWaterfall.Gui.EtoForms.Gtk/debug
